package org.example.gui;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;


public class BlueScanWindow extends JFrame {
    private JComboBox<String> adapterComboBox;
    private JButton scanButton;
    private JButton stopButton;
    private JTable devicesTable;
    private DefaultTableModel tableModel;

    private volatile boolean isScanning = false;

    public BlueScanWindow() {
        super("BLE Scanner");
        setSize(800, 600);

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initUI();
        initBluetooth();
    }

    private void initUI() {
        // Панель выбора адаптера
        JPanel topPanel = new JPanel(new FlowLayout());
        adapterComboBox = new JComboBox<>();
        scanButton = new JButton("Сканировать");
        stopButton = new JButton("Остановить");
        stopButton.setEnabled(false);
        topPanel.add(new JLabel("Адаптер:"));
        topPanel.add(adapterComboBox);
        topPanel.add(scanButton);
        topPanel.add(stopButton);

        // Таблица устройств
        String[] columns = {"Адрес", "Имя", "RSSI", "Данные"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        devicesTable = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(devicesTable);

        // Обработчики событий
        stopButton.addActionListener(e -> stopScanning());

        add(topPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
    }

    private void initBluetooth() {

    }




    private void stopScanning() {

    }

    private void updateTable() {

    }



    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new BlueScanWindow().setVisible(true));
    }





    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
