package org.example.gui.settings.updates;

import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.extern.slf4j.Slf4j;
import org.example.utilites.properties.MyProperties;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;

@Component
@Slf4j
public class UpdateSettingsWindow extends JDialog {
    private final UpdateSettingsPanel panel = new UpdateSettingsPanel();
    private JPanel updateSettingsContainer;

    public UpdateSettingsWindow() {
        setModal(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        JPanel content = new JPanel(new BorderLayout());
        JPanel root = panel.getSubContainer();
        if (root != null) {
            content.add(root, BorderLayout.CENTER);
        }

        JButton saveButton = new JButton("Сохранить");
        content.add(saveButton, BorderLayout.SOUTH);

        setContentPane(content);
        setMinimumSize(new Dimension(450, 350));
        pack();

        loadValues();

        saveButton.addActionListener(e -> onSave());
    }

    private void loadValues() {
        MyProperties props = MyProperties.getInstance();
        if (props == null) {
            log.warn("MyProperties is null, используем умолчания");
            panel.gitflicKeyVal.setText("1d691a01-16a4-45df-b9c3-b9f24c6a8bfb");
            panel.repoGitflicVal.setText("https://gitflic.ru/project/andrewkantser/elephant-monitor/release?sort=TIME&direction=DESC");
            panel.repoGithubVal.setText("https://api.github.com/repos/andrewoficial/my_first_microservice_app/releases?per_page=100");
            return;
        }
        panel.gitflicKeyVal.setText(props.getGitflicToken());
        panel.githubKeyVal.setText(props.getGithubToken());
        panel.giteaKeyVal.setText(props.getGiteaToken());
        panel.repoGitflicVal.setText(props.getGitflicRepo());
        panel.repoGithubVal.setText(props.getGithubRepo());
        panel.repoGiteaVal.setText(props.getGiteaRepo());
    }

    private void onSave() {
        MyProperties props = MyProperties.getInstance();
        if (props == null) {
            JOptionPane.showMessageDialog(this, "Настройки недоступны");
            return;
        }
        props.setGitflicToken(panel.gitflicKeyVal.getText());
        props.setGithubToken(panel.githubKeyVal.getText());
        props.setGiteaToken(panel.giteaKeyVal.getText());
        props.setGitflicRepo(panel.repoGitflicVal.getText());
        props.setGithubRepo(panel.repoGithubVal.getText());
        props.setGiteaRepo(panel.repoGiteaVal.getText());

        JOptionPane.showMessageDialog(this, "Настройки обновлений сохранены");
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        updateSettingsContainer = new JPanel();
        updateSettingsContainer.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return updateSettingsContainer;
    }
}
