#General Settings
#Fri Jun 06 13:45:23 GMT+03:00 2025
baudRate=75, 9600, 9600
baudRateCode=0, 8, 8
clientAssociationID=0, 0, 0, 0
clientAssociationMarkers=
clientId=503382, 501956, 502481
command=, SREV?, REBOOT
csvLogInputASCII=false
csvLogInputParsed=true
csvLogOutputASCII=false
csvLogSeparator=;
csvLogState=true
dataBits=5, 8, 8
dataBitsCode=0, 3, 3
dbgLogInputASCII=true
dbgLogInputHEX=false
dbgLogInputParsed=false
dbgLogOutputASCII=true
dbgLogOutputHEX=false
dbgLogSeparator=\t
dbgLogState=true
drv=jdbc\:postgresql\://
idents=
logLevel=DEBUG
needSyncSavingAnswer=false
parityBit=NO, NO, NO
parityBitCode=0, 0, 0
ports=COM12, COM12, COM41
prefix=, , 
protocol=IGM10ASCII, GPS_Test, GPS_Test
protocolCode=0, 8, 8
prt=8075
pwd=1234
stopBits=1, 1, 1
stopBitsCode=0, 0, 0
syncSavingAnswerTimerLimitMS=1000
syncSavingAnswerWindowMS=100000
tabCounter=2
tabNumber=4, 1, 0
tabNumbersIdents=
url=127.0.0.1
usr=user
vegaAddress=ws\://127.0.0.1\:8002
vegaLogin=root
vegaPassword=123
