#General Settings
#Mon Feb 10 14:14:53 GMT+03:00 2025
baudRate=57600
baudRateCode=11
clientAssociationID=0, 0
clientAssociationMarkers=
commands=F
csvLogInputASCII=false
csvLogInputParsed=true
csvLogOutputASCII=false
csvLogSeparator=;
csvLogState=true
dataBits=8
dataBitsCode=3
dbgLogInputASCII=true
dbgLogInputHEX=true
dbgLogInputParsed=false
dbgLogOutputASCII=false
dbgLogOutputHEX=false
dbgLogSeparator=\t
dbgLogState=true
drv=
idents=
logLevel=DEBUG
needSyncSavingAnswer=true
parityBit=NO
parityBitCode=0
ports=COM29, COM28
prefixes=, 001
protocol=ARD_TERM
protocolCode=5
prt=
pwd=
stopBits=1
stopBitsCode=0
syncSavingAnswerTimerLimitMS=1000
syncSavingAnswerWindowMS=100000
tabCounter=1
tabNumbersIdents=
url=
usr=
