name: Test Build

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug - List files (PowerShell)
      run: |
        Write-Host "=== Current directory ==="
        Get-Location
        Write-Host "=== Root directory contents ==="
        Get-ChildItem
        Write-Host "=== Scripts directory ==="
        Get-ChildItem scripts -ErrorAction SilentlyContinue
        Write-Host "=== Installer directory ==="
        Get-ChildItem installer -ErrorAction SilentlyContinue
        Write-Host "=== Recursive file listing ==="
        Get-ChildItem -Recurse -Name -ErrorAction SilentlyContinue
